apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: admin@vamshi.com
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - http01:
        ingress:
          class: nginx
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: dashboard-vamshi-tls
  namespace: default
spec:
  secretName: dashboard-vamshi-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: dashboard.vamshi.com
  dnsNames:
  - dashboard.vamshi.com
