apiVersion: apps/v1
kind: Deployment
metadata:
  name: ptfd-app
  labels:
    app: ptfd-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ptfd-app
  template:
    metadata:
      labels:
        app: ptfd-app
    spec:
      containers:
      - name: ptfd-app
        image: ghcr.io/1308harshit/ptfd:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8501
        env:
        - name: STREAMLIT_SERVER_ENABLE_CORS
          value: "true"
        - name: STREAMLIT_SERVER_HEADLESS
          value: "true"
        - name: STREAMLIT_SERVER_PORT
          value: "8501"
        - name: STREAMLIT_SERVER_BASE_URL_PATH
          value: "/"
        resources:
          limits:
            cpu: "2"
            memory: "512Mi"
          requests:
            cpu: "1"
            memory: "256Mi"
